server:
  port: 8083
  
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: Hari@0907
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8086 
 
 

   
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-63106055.okta.com/oauth2/default
    audience: api://default
  